#!/bin/bash

# let your config take place here
tunnel_1=("localhost" "12345" "serverhost" "12345")

# --- killing ---
# old tunnels must die

ps aux | grep "ssh -D" | head -n -1 >| /dev/null 2>| /dev/null
if [ $? -eq 0 ]
then
    echo "killing all old tunnels..."
    pids=$(ps aux | grep "ssh -D.*" | head -n -1 | awk '{print $2}')
    for pid in $(echo ${pids})
    do
        echo "PID: $(tput bold)$pid$(tput sgr0)"
        kill $pid
    done
fi

# --- digging ---
# for more copy this and
# increase tunnel number
# -----------8<-----------------

echo "seting up tunnels..."
echo -n "$(tput setaf 4)\
${tunnel_1[0]}:$(tput bold)$(tput setaf 7)\
${tunnel_1[1]} $(tput sgr0)--> $(tput setaf 5)\
${tunnel_1[2]}:$(tput bold)$(tput setaf 7)\
${tunnel_1[3]}\
$(tput sgr0)...."

ssh -D${tunnel_1[1]} -NCf -p${tunnel_1[3]} ${tunnel_1[2]}

if [ $? -eq 0 ]
then
    echo "$(tput setaf 2)OK$(tput sgr0)"
else
    echo "$(tput setaf 1)FAIL$(tput sgr0)"
fi

# -------------->8--------------
