#!/bin/bash

# --- config ---
# let your config take place in $HOME/.tunnels.conf
# maybe with out user for usage with user who calls
# e.g.
# bindhost 12345 serverhost 12345 user

# --- functions ---
function dyn()
{
    if [ $# -eq 6 ]
    then
        user=$(echo -n "${6}@")
    elif [ $# -eq 5 ]
    then
        user=""
    else
        echo "~/.tunnels.conf not readable\nnot enough arguments" >&2
        return 2
    fi
    echo "[$(tput setaf 202)${1}$(tput sgr0)] $(tput setaf 238)${2} $(tput\
        bold)$(tput setaf 7)${3}$(tput sgr0) --> $(tput setaf\
        14)${user}$(tput setaf 129)${4} $(tput bold)$(tput\
        setaf 7)${5}$(tput sgr0)...."

    ssh -D${2}:${3} -NCf -p${5} ${user}${4}
}

function loc()
{
    if [ $# -eq 8 ]
    then
        user=$(echo -n "${8}@")
    elif [ $# -eq 7 ]
    then
        user=""
    else
        echo "~/.tunnels.conf not readable\n not enough arguments" >&2
        return 2
    fi
    echo "[$(tput setaf 215)${1}$(tput sgr0)] $(tput setaf 238)${2} $(tput\
        bold)$(tput setaf 7)${3}:${4}:${5}$(tput sgr0) --> $(tput setaf\
        14)${user}$(tput setaf 129)${6} $(tput bold)$(tput\
        setaf 7)${7}$(tput sgr0)...."

    ssh -L${2}:${3}:${4}:${5} -NCf -p${7} ${user}${6}
}

function rem()
{
    # TODO
    echo "$(tput setab 220)$(tput setaf 0)TODO$(tput sgr0)"
    return 2
}

function dig()
{

    if [ ${1} == "dyn" ]
    then
        dyn $@
    elif [ ${1} == "loc" ]
    then
        loc $@
    elif [ ${1} == "rem" ]
    then
        rem $@
    else
        echo "~/.tunnels.conf not readable" >&2
        return 2
    fi

    ret=$?

    if [ $ret -eq 0 ]
    then
        echo "[CHECK $(tput setaf 10)$(tput bold)✔$(tput sgr0)]"
    else
        echo "[FAIL $(tput setaf 9)$(tput bold)✘$(tput sgr0)]"
    fi
}

# --- killing ---
# old tunnels must die

ps aux | grep "ssh \(-L.*\|-D.*\)" | grep -v "grep" >| /dev/null 2>| /dev/null
if [ $? -eq 0 ]
then
    echo "killing all old tunnels..."
    pids=$(ps aux | grep "ssh \(-L.*\|-D.*\)" | grep -v "grep" | awk '{print $2}')
    for pid in $(echo ${pids})
    do
        echo "PID: $(tput bold)$pid$(tput sgr0)"
        kill $pid
    done
fi

# --- digging ---

echo -e "\nsetting up tunnels..."
if [ -f "$HOME/.tunnels.conf" ]
then
    while read line
    do
        if [[ ! "'${line}'" =~ ^\'(\s*#.*|\s*)\' ]]
        then
            dig $(echo ${line[@]})
        fi
    done < "$HOME/.tunnels.conf"
    exit 0
else
    echo "no ~/.tunnels.conf was found" >&2
    exit 1
fi
